# Generated by Django 5.2.6 on 2025-10-23 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("election", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="candidate",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="candidates/"),
        ),
    ]
