# Generated by Django 5.2.6 on 2025-10-23 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("election", "0002_candidate_image"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="voter",
            name="has_voted",
        ),
        migrations.AddField(
            model_name="voter",
            name="has_voted_positions",
            field=models.ManyToManyField(blank=True, to="election.position"),
        ),
    ]
