# Generated by Django 5.2.6 on 2025-10-24 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("election", "0003_remove_voter_has_voted_voter_has_voted_positions"),
    ]

    operations = [
        migrations.AddField(
            model_name="voter",
            name="is_verified",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="voter",
            name="otp",
            field=models.CharField(blank=True, max_length=6),
        ),
    ]
